repositories:
  Leap:
    project: openSUSE:Leap:15.5
    repository: standard
  Uyuni_Other:
    project: systemsmanagement:Uyuni:Master:Other
    repository: openSUSE_Leap_15.5
  Uyuni:
    project: systemsmanagement:Uyuni:Master
    repository: openSUSE_Leap_15.5
  Leap_sle:
    url: https://download.opensuse.org/update/leap/15.5/sle
artifacts:
  - artifact: simple-core
    # How comes that package is not noarch?
    arch: x86_64
    repository: Uyuni_Other
  - artifact: lucene-core
    jar: lucene-core
    package: lucene
    repository: Uyuni_Other
  - artifact: lucene-analyzers
    jar: lucene-analyzers
    package: lucene
    repository: Uyuni_Other
  - artifact: commons-lang3
    package: apache-commons-lang3
    repository: Leap
  - artifact: commons-logging
    package: apache-commons-logging
    jar: apache-commons-logging\.jar
    repository: Leap
  - artifact: redstone-xmlrpc
    jar: redstone-xmlrpc-[0-9.]+
    repository: Uyuni_Other
  - artifact: mybatis
    package: mybatis
    repository: Uyuni_Other
  - artifact: quartz
    repository: Uyuni_Other
  - artifact: log4j-core
    jar: log4j-core.jar
    package: log4j
    repository: Leap
  - artifact: log4j-api
    jar: log4j-api.jar
    package: log4j
    repository: Leap
  - artifact: c3p0
    repository: Leap
  - artifact: mchange-commons-java
    package: mchange-commons
    repository: Leap
  - artifact: picocontainer
    repository: Uyuni_Other
  - artifact: javassist
    repository: Leap_sle
  - artifact: apache-commons-ognl
    repository: Leap
  - artifact: postgresql-jdbc
    repository: Leap
  - artifact: client
    package: ongres-scram-client
    repository: Leap
  - artifact: common
    package: ongres-scram
    repository: Leap
  - artifact: stringprep
    package: ongres-stringprep
    repository: Leap
  - artifact: saslprep
    package: ongres-stringprep-saslprep
    repository: Leap
  - artifact: log4j-slf4j-impl
    jar: log4j-slf4j-impl.jar
    package: log4j-slf4j
    repository: Leap
  - artifact: slf4j-api
    package: slf4j
    jar: api
    repository: Leap
