name: Checksum checks

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'containers/mlm-supportconfig/kubectl-mlm_supportconfig*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Validate the checksums
        run: |
          cd containers/mlm-supportconfig
          sha512sum -c kubectl-mlm_supportconfig.sha512
