name: Python checkstyle

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**.py'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/systemsmanagement/uyuni/master/docker/containers_tw/uyuni-master-python:latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

    - id: files
      uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c #v2.3.0
      with:
        # Remember to keep the filter aligned with CODEOWNERS
        filter:  |
          *.py
          !mgr_bootstrap_data.py
          !testsuite/**
    
    - name: Run black on files
      if: ${{ steps.files.outputs.added_modified_renamed }}
      run: black --check --diff -t py36 ${{ steps.files.outputs.added_modified_renamed }}

    - name: Run pylint on files
      if: ${{ steps.files.outputs.added_modified_renamed }}
      run: pylint --rcfile=/root/.pylintrc ${{ steps.files.outputs.added_modified_renamed }}

