name: RuboCop

on:
  pull_request:
    paths:
      - '.github/workflows/rubocop.yml'
      - 'testsuite/features/**.rb'
      - 'testsuite/.rubocop.yml'
      - 'testsuite/.rubocop_todo.yml'
      - 'testsuite/Gemfile'
      - 'testsuite/Rakefile'

jobs:
  rubocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - uses: ruby/setup-ruby@0481980f17b760ef6bca5e8c55809102a0af1e5a # v1.263.0
      with:
        ruby-version: '3.3'

    - name: Install and Run RuboCop
      run: |
        cd testsuite
        gem install bundler
        bundle install
        bundle exec rubocop --version
        bundle exec rubocop features/*
