name: RuboCop

on:
  pull_request:
    paths:
      - '.github/workflows/rubocop.yml'
      - 'testsuite/features/**.rb'
      - 'testsuite/.rubocop.yml'
      - 'testsuite/.rubocop_todo.yml'
      - 'testsuite/Gemfile'
      - 'testsuite/Rakefile'

jobs:
  rubocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
    - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 #v1.300.0
      with:
        ruby-version: '3.3'

    - name: Install and Run RuboCop
      run: |
        cd testsuite
        gem install bundler
        bundle install
        bundle exec rubocop --version
        bundle exec rubocop features/*
