name: Search server compile

on:
  push:
    branches:
      - master
    paths:
      - 'search-server/spacewalk-search/**.java'
      - 'search-server/spacewalk-search/**.xml'
      - '.github/workflows/search-server-compile.yml'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'search-server/spacewalk-search/**.java'
      - 'search-server/spacewalk-search/**.xml'
      - '.github/workflows/search-server-compile.yml'

jobs:
  compile:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/systemsmanagement/uyuni/master/docker/containers/uyuni-master-pgsql:latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
      with:
        path: search-server/spacewalk-search/buildconf
        key: ${{ runner.os }}-spacewalk-search-buildconf-${{ hashFiles('search-server/spacewalk-search/buildconf/*.*') }}

    - name: Resolve dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: ant -f search-server/spacewalk-search/build.xml resolve

    - name: Compile
      run: ant -f search-server/spacewalk-search/build.xml compile
