name: Generate YARD Documentation

on:
  push:
    branches:
      - master

jobs:
  generate_documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@6797dcbb9a1889fd411d07e8aba7eded53fb8b48 #v1.264.0
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: |
          sudo apt-get install -y rdoc
          gem install yard yard-cucumber

      - name: Generate .yard/config
        run: |
          mkdir $HOME/.yard
          echo '--- !ruby/hash-with-ivars:SymbolHash
          elements:
            :load_plugins: true
            :ignored_plugins: []
            :autoload_plugins: []
            :safe_mode: false
            :"yard-cucumber":
              language:
                step_definitions: [ "Given", "When", "Then", "And", "But"]
              menus: [ "features", "directories", "tags", "steps", "step definitions" ]
          ivars:
            :@symbolize_value: false%' > $HOME/.yard/config

      - name: Generate YARD Documentation
        run: |
          cd testsuite
          yard doc --protected --private features/step_definitions/*.rb features/support/*.rb features/support/**/*.rb features/**/*.feature features/**/**/*.feature

      - name: Archive documentation as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 #v5.0.0
        with:
          name: yard-docs
          path: testsuite/doc
